# sudo: required

# blocklist

# safelist
branches:
 only:
 - master

# except:
# - gh-pages

#  only:
#  - gh-pages
#  - /.*/

language: cpp

compiler: gcc

cache:
  - apt
  - ccache

matrix:
  include:
  - os: osx
  - os: linux

# addons:
#   apt:
#     packages:
#      - build-essential
#      - libtool
#      - automake
#      - gfortran
#      - libglu1-mesa-dev
#      - libfreetype6-dev
#      - uuid-dev
#      - libxmu-dev
#      - libxmu-headers
#      - libxi-dev
#      - libx11-dev
#      - libxt-dev
#      - libxaw7-dev
#      - liblapack-dev
#      - tcsh
#      - curl
#      - git
#      - libxml2-utils

before_install:
  # on osx use brew to install autotools and compiler
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
       brew update ;
       brew install hub;
    fi

# install:
#  # install pre-built packages needed to compile freesurfer
#  - ./travis/packages.sh

script:
  # configure and compile freesurfer (removedfor this example)
  # test doing dake build then install step via script
  travis_wait 30 ./src/build.sh

# add a timestamp tage before deploy
before_deploy:
  - git config --local user.name "buildqa"
  - git config --local user.email "buildqa@contbay.com"
  # create year-month-day tag, allow to fail if already exists ( >1 build per day)
  # - hub release create -m "Travis CI build" "$(date +'%Y-%m-%d')" || true
  - git tag "$(date +'%Y%-m%-d')" || true
  - ./delete_asset.py buildqa tester1 "$(date +'%Y%-m%-d')" darwin.tgz
  # upload assets to existing tar
  # - ./upload-github-release-asset.sh owner=buildqa repo=tester1 filename=./install/darwin.tgz tag="$(date +'%Y-%m-%d')" github_api_token="$GITHUB_TOKEN"
  # - bash -x upload-github-release-asset.sh

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  overwrite: true
  file: "./install/darwin.tgz"
  skip_cleanup: true


